### ISSUE TITLE
유저 정보 recoil 업데이트 개선

### ISSUE THREAD

**Issue by kyw0716** [kyw0716/Youngstagram#59]
새로고침시 로그인 된 유저 정보가 사라지는것을 방지하고자 임시방편으로 유저 정보를 사용하는 모든 컴포넌트에서 setRecoilState를 해주었는데 성능 개선을 위해 가장 root 디렉토리에서 한번만 수행하도록 바꿔야함

**Comment by kyw0716** [comment]
https://github.com/kyw0716/Youngstagram/pull/64

**Comment by Cutiepazzipozzi** [comment]
멋져요~~~~~

**Comment by kyw0716** [comment]
사용자 정보가 업데이트 됐을 때 loading페이지에서 다시 사용자 정보 로드하기

- [ ] 프로필 이미지, 닉네임 변경
- [ ] 이미지 업로드
- [ ] 팔로우
